In [35]:
import pandas as pd
import json

df = pd.read_csv("data/cross/test_indo.csv")
df['dataset_id'] = df['dataset_num'].str.extract(r'-(\d+)$').astype(int)
df = df[['dataset_id', 'answer', 'normalized_score']]
df.head()
result = (
    df.groupby('dataset_id')
    .apply(lambda group: [{"answer": row['answer'], "score": row['normalized_score']} for _, row in group.iterrows()])
    .to_dict()
)

# convert keys to strings (optional but matches your example)
result = {str(k): v for k, v in result.items()}

# save to JSON
with open("answer_cross.json", "w", encoding="utf-8") as f:
    json.dump(result, f, indent=4, ensure_ascii=False)

C:\Users\User\AppData\Local\Temp\ipykernel_5264\3923337473.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda group: [{"answer": row['answer'], "score": row['normalized_score']} for _, row in group.iterrows()])


In [ ]:
import torch
import torch.nn.functional as F

hidden_states = torch.randn(1, 3, 5)

attn_linear = torch.nn.Linear(5, 1)

attn_scores = attn_linear(hidden_states).squeeze(-1)

attn_weights = F.softmax(attn_scores, dim=1).unsqueeze(-1)

pooled = torch.sum(hidden_states * attn_weights, dim=1)

print("Hidden states:\n", hidden_states)
print(attn_linear.weight)
print("Attention scores:\n", attn_scores)
print("Attention weights:\n", attn_weights)
print("Pooled output:\n", pooled)


Hidden states:
 tensor([[[-9.7118e-01, -1.9843e+00,  1.2923e+00, -9.0187e-01, -6.6999e-02],
         [ 1.5672e+00,  1.3224e-03, -1.3752e+00,  3.9771e-01, -3.8122e-02],
         [ 1.4740e+00,  9.0574e-01, -3.2328e-01, -1.6604e-01,  6.7145e-01]]])
Parameter containing:
tensor([[ 0.3029, -0.2943,  0.2611, -0.2435,  0.4013]], requires_grad=True)
Attention scores:
 tensor([[1.0351, 0.2182, 0.6205]], grad_fn=<SqueezeBackward1>)
Attention weights:
 tensor([[[0.4757],
         [0.2101],
         [0.3142]]], grad_fn=<UnsqueezeBackward0>)
Pooled output:
 tensor([[ 0.3305, -0.6590,  0.2241, -0.3976,  0.1711]], grad_fn=<SumBackward1>)
